---
hugo_env: &hugo_env
   BASE_URL: https://tommy-drone-builds.s3.amazonaws.com/

kind: pipeline
name: hugo-website
steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL
    volumes:
      - name: build-artifacts
        path: /build

  - name: deploy-to-s3
    image: amazon/aws-cli:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN:
        from_secret: AWS_SESSION_TOKEN
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - echo "Deploying Hugo site to S3..."
      - aws s3 sync public/ s3://tommy-drone-builds --delete
      - aws s3 website s3://tommy-drone-builds --index-document index.html --error-document 404.html
      - echo "Deployment completed successfully!"
    volumes:
      - name: build-artifacts
        path: /build
    depends_on:
      - hugo-build
    when:
      event: push
      branch: master

  - name: display_urls
    image: lowess/drone-tabulate
    environment:
      <<: *hugo_env
    settings:
      headers:
        - URL
      rows:
        -
          - "S3 Website"
          - https://tommy-drone-builds.s3.amazonaws.com/index.html
        -
          - "S3 Bucket"
          - https://s3.console.aws.amazon.com/s3/buckets/tommy-drone-builds
    when:
      event: push
      branch: master

volumes:
  - name: build-artifacts
    temp: {}
